# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_knapsack_rcpp_hello_world`)
}

#' Algorithme Brut Force using C++
#'
#' @param poids vecteur contenant les poids des objets
#' @param valeurs vecteur contenant les valeurs (numériques) des objets
#' @param poids_max représente le poids maximal autorisé dans le sac
#' @return La solution optimale
#' @export
rcpp_sac_a_dos <- function(poids, valeurs, poids_max) {
    .Call(`_knapsack_rcpp_sac_a_dos`, poids, valeurs, poids_max)
}

#' Algorithme Dynamic Programmation using C++
#'
#' @param poids vecteur contenant les poids des objets
#' @param valeurs vecteur contenant les valeurs (numériques) des objets
#' @param poids_max représente le poids maximal autorisé dans le sac
#' @param precision represente la precision
#' @return La solution optimale
#' @export
rcpp_sac_a_dos_dp <- function(poids, valeurs, poids_max, precision = 1000L) {
    .Call(`_knapsack_rcpp_sac_a_dos_dp`, poids, valeurs, poids_max, precision)
}

#' Algorithme Glouton using C++
#'
#' @param poids vecteur contenant les poids des objets
#' @param valeurs vecteur contenant les valeurs (numériques) des objets
#' @param poids_max représente le poids maximal autorisé dans le sac
#' @return Une solution... optimale ?
#' @export
rcpp_sac_a_dos_glouton <- function(poids, valeurs, poids_max) {
    .Call(`_knapsack_rcpp_sac_a_dos_glouton`, poids, valeurs, poids_max)
}

